# Docker Compose version
version: '3'

# Services to be spun up when running `docker-compose up`
services:
  # Service name (use lowercase)
  botiga-server:
    # Image Name
    image: botiga-server:latest

    # fixing name of container
    container_name: botiga-server

    # Build the Docker image using the Dockerfile present in the current directory
    build:
      context: .
      dockerfile: Dockerfile.local # Used this file to build the image

    # Map port 3000 of the host to port 3000 of the container
    ports:
      - '3000:3000'

    # Use an environment file for setting environment variables
    env_file: .env

    # Override or add environment variables
    environment:
      # Google Cloud credentials for Firebase
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-config.json
      # Port on which the application should run
      - PORT=3000

    # Volumes to be mounted into the container
    volumes:
      # Mount the JSON file for Firebase into the specified directory in the container
      - ./.firesdk-dev-admin.json:/app/firebase-config.json

      # Mount the code directory into the specified directory in the container to reflect any changes in code immediately in container
      - type: bind
        source: ./src
        target: /usr/app/src
        read_only: true
      # ./src:/usr/app/src # Map .:/usr/app do not work as node_modules local vs one in container clash
